repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", "src/", "backend/", "-c", ".bandit.yaml"]
        pass_filenames: false
        exclude: ^tests/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["--branch", "main"]

  - repo: local
    hooks:
      - id: no-ml-artifacts
        name: Bloquer artefacts ML (.pkl, .joblib, .h5)
        language: fail
        entry: "Artefact ML interdit dans Git"
        files: '\.(pkl|joblib|h5|onnx|pt|pth)$'
